apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-lm
  namespace: lm-webstack
  labels:
    app: api-lm
    project: milestone2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-lm
  template:
    metadata:
      labels:
        app: api-lm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api
        image: api-lm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_URL
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: api-config-lm
              key: DATABASE_PASSWORD
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-lm
  namespace: lm-webstack
  labels:
    app: api-lm
spec:
  selector:
    app: api-lm
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 