apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lm
  namespace: lm-webstack
  labels:
    app: frontend-lm
    project: milestone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-lm
  template:
    metadata:
      labels:
        app: frontend-lm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: frontend
        image: frontend-lm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-config-lm
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lm
  namespace: lm-webstack
  labels:
    app: frontend-lm
spec:
  selector:
    app: frontend-lm
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort 