apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-lm
  namespace: lm-webstack
  labels:
    app: postgres-lm
    project: milestone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-lm
  template:
    metadata:
      labels:
        app: postgres-lm
    spec:
      containers:
      - name: postgres
        image: postgres-lm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config-lm
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret-lm
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-lm
              key: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc-lm
      - name: init-script
        configMap:
          name: postgres-init-lm
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lm
  namespace: lm-webstack
  labels:
    app: postgres-lm
spec:
  selector:
    app: postgres-lm
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 