apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-lm
  namespace: lm-webstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 